// Generated by CoffeeScript 1.6.2
/*
Main entry point
*/


(function() {
  var Store;

  Store = require('./store');

  module.exports = {
    Store: Store,
    store: function(settings) {
      if (settings == null) {
        settings = {};
      }
      return new Store(settings);
    }
  };

}).call(this);
